//! Fixed category-owned UCI declarations; see docs/base-uci-observations.md.
use crate::definition::{uci_read, uci_read_with_options};
use openwrt_mcp_core::{Operation, uci::UciReadProfile};

pub(super) fn operations() -> Vec<Operation> {
    vec![
        uci_read_with_options(
            "network_device_configuration",
            1,
            UciReadProfile::NetworkDevices,
            &[
                ("name", 256),
                ("type", 64),
                ("ifname", 256),
                ("vid", 32),
                ("mtu", 32),
                ("mtu6", 32),
                ("macaddr", 17),
                ("enabled", 8),
                ("ipv6", 8),
                ("stp", 8),
                ("stp_kernel", 8),
                ("stp_proto", 64),
                ("forward_delay", 32),
                ("priority", 32),
                ("ageing_time", 32),
                ("igmp_snooping", 8),
                ("multicast_querier", 8),
                ("bridge_empty", 8),
                ("vlan_filtering", 8),
            ],
            &[
                ("ports", 256),
                ("ingress_qos_mapping", 256),
                ("egress_qos_mapping", 256),
            ],
        ),
        uci_read_with_options(
            "network_bridge_vlan_configuration",
            1,
            UciReadProfile::BridgeVlans,
            &[("device", 256), ("vlan", 32), ("local", 8)],
            &[("ports", 256), ("alias", 256)],
        ),
        uci_read(
            "network_route_v4_configuration",
            UciReadProfile::RoutesV4,
            &[
                ("interface", 256),
                ("target", 256),
                ("netmask", 64),
                ("gateway", 256),
                ("metric", 32),
                ("mtu", 32),
                ("table", 64),
                ("valid", 32),
                ("source", 256),
                ("onlink", 8),
                ("type", 64),
                ("proto", 64),
                ("disabled", 8),
            ],
        ),
        uci_read(
            "network_route_v6_configuration",
            UciReadProfile::RoutesV6,
            &[
                ("interface", 256),
                ("target", 256),
                ("netmask", 64),
                ("gateway", 256),
                ("metric", 32),
                ("mtu", 32),
                ("table", 64),
                ("valid", 32),
                ("source", 256),
                ("onlink", 8),
                ("type", 64),
                ("proto", 64),
                ("disabled", 8),
            ],
        ),
        uci_read(
            "network_rule_v4_configuration",
            UciReadProfile::RulesV4,
            &[
                ("in", 256),
                ("out", 256),
                ("invert", 8),
                ("src", 256),
                ("dest", 256),
                ("priority", 32),
                ("tos", 32),
                ("mark", 64),
                ("lookup", 64),
                ("suppress_prefixlength", 32),
                ("uidrange", 64),
                ("action", 64),
                ("goto", 32),
                ("ipproto", 64),
                ("sport", 64),
                ("dport", 64),
                ("disabled", 8),
            ],
        ),
        uci_read(
            "network_rule_v6_configuration",
            UciReadProfile::RulesV6,
            &[
                ("in", 256),
                ("out", 256),
                ("invert", 8),
                ("src", 256),
                ("dest", 256),
                ("priority", 32),
                ("tos", 32),
                ("mark", 64),
                ("lookup", 64),
                ("suppress_prefixlength", 32),
                ("uidrange", 64),
                ("action", 64),
                ("goto", 32),
                ("ipproto", 64),
                ("sport", 64),
                ("dport", 64),
                ("disabled", 8),
            ],
        ),
    ]
}
