//! Synthetic supplied streams only. Test producers are not production APIs.
mod boundaries;
mod malformed;

use super::archive::{header, member, terminated};
use flate2::{Compression, write::GzEncoder};
use openwrt_mcp_device_codec::{
    archive::{ArchiveError, ExpectedArchive, ExpectedFile},
    gzip::{GzipArchiveSummary, GzipArchiveValidator, GzipError, MAX_CHUNK_BYTES},
};
use std::io::Write;

fn validator(size: u64) -> GzipArchiveValidator {
    GzipArchiveValidator::new(
        ExpectedArchive::new(&[ExpectedFile::new("fixture/a", size).unwrap()]).unwrap(),
    )
}
fn check(bytes: &[u8], size: u64, chunk: usize) -> Result<GzipArchiveSummary, GzipError> {
    let mut v = validator(size);
    for part in bytes.chunks(chunk) {
        v.feed(part)?;
    }
    v.finish()
}
fn compressed(bytes: &[u8]) -> Vec<u8> {
    let mut encoder = GzEncoder::new(Vec::new(), Compression::best());
    encoder.write_all(bytes).unwrap();
    encoder.finish().unwrap()
}
// Independent bitwise fixture CRC, never linked into the shipped decoder.
fn crc(bytes: &[u8]) -> u32 {
    let mut value = !0_u32;
    for byte in bytes {
        value ^= u32::from(*byte);
        for _ in 0..8 {
            value = (value >> 1) ^ (0xedb88320 & (0_u32.wrapping_sub(value & 1)));
        }
    }
    !value
}
fn stored(bytes: &[u8]) -> Vec<u8> {
    assert!(!bytes.is_empty());
    let mut gzip = vec![0x1f, 0x8b, 8, 0, 0, 0, 0, 0, 0, 255];
    let count = bytes.len().div_ceil(65535);
    for (index, part) in bytes.chunks(65535).enumerate() {
        gzip.push(u8::from(index + 1 == count));
        gzip.extend_from_slice(&(part.len() as u16).to_le_bytes());
        gzip.extend_from_slice(&(!(part.len() as u16)).to_le_bytes());
        gzip.extend_from_slice(part);
    }
    gzip.extend_from_slice(&crc(bytes).to_le_bytes());
    gzip.extend_from_slice(&(bytes.len() as u32).to_le_bytes());
    gzip
}
fn optional(base: &[u8], flags: u8, extra: &[u8], name: &[u8], comment: &[u8]) -> Vec<u8> {
    let mut bytes = base[..10].to_vec();
    bytes[3] = flags;
    if flags & 4 != 0 {
        bytes.extend_from_slice(&(extra.len() as u16).to_le_bytes());
        bytes.extend_from_slice(extra);
    }
    if flags & 8 != 0 {
        bytes.extend_from_slice(name);
    }
    if flags & 16 != 0 {
        bytes.extend_from_slice(comment);
    }
    if flags & 2 != 0 {
        bytes.extend_from_slice(&(crc(&bytes) as u16).to_le_bytes());
    }
    bytes.extend_from_slice(&base[10..]);
    bytes
}
fn fixed_fixture() -> Vec<u8> {
    // Produced independently with Python tarfile USTAR + zlib 1.3 Z_FIXED,
    // wbits=31, level=9. One fixture/a regular file contains b"public\n".
    // Expanded archive=10240 bytes. This literal is not generated by flate2.
    let hex = "1f8b08000000000002034bcbac28292d4ad54f64a01d300002330303306d8049038139121b246e6e6a66cca060c04007505a5c925804b49261648282d2a49ccc642e8651300a46c1281805a360148c8251300a46c1281805a360148c8251300a46c1281805a360148c8251300a46c1281805a360148c8251300a46c1281805430b000044f1b73c00280000";
    hex.as_bytes()
        .as_chunks::<2>()
        .0
        .iter()
        .map(|p| u8::from_str_radix(std::str::from_utf8(p).unwrap(), 16).unwrap())
        .collect()
}

#[test]
fn stored_fixed_and_dynamic_streams_return_only_complete_counts() {
    assert_eq!(crc(b"123456789"), 0xcbf43926);
    let stored = stored(&terminated(member("fixture/a", b"public\n", false)));
    let fixed = fixed_fixture();
    let payload: Vec<_> = (0..32768).map(|i| (i % 251) as u8).collect();
    let dynamic = compressed(&terminated(member("fixture/a", &payload, false)));
    for (bytes, size, kind) in [(&stored, 7, 0), (&fixed, 7, 1), (&dynamic, 32768, 2)] {
        assert_eq!((bytes[10] >> 1) & 3, kind);
        let result = check(bytes, size, 17).unwrap();
        assert_eq!(result.compressed_bytes, bytes.len() as u64);
        assert_eq!(result.files, 1);
        assert_eq!(result.payload_bytes, size);
        let text = format!("{result:?}");
        assert!(!text.contains("fixture/a") && !text.contains("public"));
    }
    assert_eq!(check(&fixed, 7, 1).unwrap().archive_bytes, 10240);
}

#[test]
fn every_optional_flag_combination_preserves_integrity_and_opaque_metadata() {
    let base = fixed_fixture();
    for flags in 0..32 {
        let bytes = optional(
            &base,
            flags,
            b"\0\xff\x1f\x8b",
            b"../not-a-host-path\xff\0",
            b"private-looking-comment\0",
        );
        let summary = check(&bytes, 7, 1).unwrap();
        assert_eq!(summary.archive_bytes, 10240);
        assert_eq!(summary.compressed_bytes, bytes.len() as u64);
    }
    let mut opaque = base;
    opaque[4..10].fill(255);
    assert!(check(&opaque, 7, 1).is_ok());
}

#[test]
fn all_two_piece_splits_and_chunk_sizes_have_identical_completion() {
    let base = optional(&fixed_fixture(), 31, b"extra", b"name\0", b"comment\0");
    let plain = terminated(member("fixture/a", b"public\n", false));
    for bytes in [base, stored(&plain), compressed(&plain)] {
        let expected = check(&bytes, 7, MAX_CHUNK_BYTES).unwrap();
        for split in 0..=bytes.len() {
            let mut v = validator(7);
            v.feed(&bytes[..split]).unwrap();
            v.feed(&[]).unwrap();
            v.feed(&bytes[split..]).unwrap();
            assert_eq!(v.finish(), Ok(expected));
        }
        for size in [1, 2, 7, 31, 127, 511, 512, 513, 4096, MAX_CHUNK_BYTES] {
            assert_eq!(check(&bytes, 7, size), Ok(expected));
        }
    }
}

#[test]
fn every_incomplete_prefix_requires_more_input_or_fails_safely() {
    for bytes in [
        fixed_fixture(),
        optional(&fixed_fixture(), 31, b"extra", b"name\0", b"comment\0"),
        stored(&terminated(member("fixture/a", b"public\n", false))),
    ] {
        for cut in 0..bytes.len() {
            assert_eq!(
                check(&bytes[..cut], 7, 17),
                Err(GzipError::IncompleteStream),
                "cut={cut}"
            );
        }
    }
}

#[test]
fn trailer_header_crc_and_compressed_corruption_cannot_report_success() {
    let base = fixed_fixture();
    for offset in base.len() - 8..base.len() {
        for bit in 0..8 {
            let mut bytes = base.clone();
            bytes[offset] ^= 1 << bit;
            assert_eq!(check(&bytes, 7, 1), Err(GzipError::InvalidData));
        }
    }
    let valid = optional(&base, 31, b"extra", b"name\0", b"comment\0");
    let header_length = valid.len() - (base.len() - 10);
    for offset in [4, header_length - 2, header_length - 1] {
        let mut bytes = valid.clone();
        bytes[offset] ^= 1;
        assert_eq!(check(&bytes, 7, 1), Err(GzipError::InvalidData));
    }
    let mut bytes = base;
    bytes[10] = 7; // Reserved DEFLATE block type, BFINAL=1.
    assert_eq!(check(&bytes, 7, 1), Err(GzipError::InvalidData));
}
