//! Fixed category-owned UCI declarations; see docs/base-uci-observations.md.
use crate::definition::{uci_read, uci_read_with_options};
use openwrt_mcp_core::{Operation, uci::UciReadProfile};

pub(super) fn operations() -> Vec<Operation> {
    vec![
        uci_read_with_options(
            "firewall_zone_configuration",
            1,
            UciReadProfile::FirewallZones,
            &[
                ("enabled", 8),
                ("name", 256),
                ("family", 32),
                ("input", 32),
                ("output", 32),
                ("forward", 32),
                ("masq", 8),
                ("masq6", 8),
                ("masq_allow_invalid", 8),
                ("mtu_fix", 8),
                ("log", 32),
                ("log_limit", 64),
                ("auto_helper", 8),
                ("counter", 8),
            ],
            &[
                ("network", 256),
                ("device", 256),
                ("subnet", 1024),
                ("masq_src", 1024),
                ("masq_dest", 1024),
                ("helper", 256),
            ],
        ),
        uci_read(
            "firewall_forwarding_configuration",
            UciReadProfile::FirewallForwardings,
            &[
                ("enabled", 8),
                ("name", 256),
                ("family", 32),
                ("src", 256),
                ("dest", 256),
            ],
        ),
        uci_read_with_options(
            "firewall_rule_configuration",
            1,
            UciReadProfile::FirewallRules,
            &[
                ("enabled", 8),
                ("name", 256),
                ("family", 32),
                ("src", 256),
                ("dest", 256),
                ("device", 256),
                ("direction", 32),
                ("ipset", 256),
                ("helper", 256),
                ("set_helper", 256),
                ("limit", 64),
                ("limit_burst", 32),
                ("utc_time", 8),
                ("start_date", 32),
                ("stop_date", 32),
                ("start_time", 32),
                ("stop_time", 32),
                ("weekdays", 128),
                ("mark", 64),
                ("set_mark", 64),
                ("set_xmark", 64),
                ("dscp", 32),
                ("set_dscp", 32),
                ("counter", 8),
                ("log", 256),
                ("log_limit", 64),
                ("target", 32),
            ],
            &[
                ("proto", 256),
                ("src_ip", 1024),
                ("src_mac", 1024),
                ("src_port", 1024),
                ("dest_ip", 1024),
                ("dest_port", 1024),
                ("icmp_type", 1024),
            ],
        ),
        uci_read_with_options(
            "firewall_redirect_configuration",
            1,
            UciReadProfile::FirewallRedirects,
            &[
                ("enabled", 8),
                ("name", 256),
                ("family", 32),
                ("src", 256),
                ("dest", 256),
                ("ipset", 256),
                ("helper", 256),
                ("src_ip", 1024),
                ("src_port", 256),
                ("src_dip", 1024),
                ("src_dport", 256),
                ("dest_ip", 1024),
                ("dest_port", 256),
                ("limit", 64),
                ("limit_burst", 32),
                ("utc_time", 8),
                ("start_date", 32),
                ("stop_date", 32),
                ("start_time", 32),
                ("stop_time", 32),
                ("weekdays", 128),
                ("mark", 64),
                ("reflection", 8),
                ("reflection_src", 32),
                ("counter", 8),
                ("log", 256),
                ("log_limit", 64),
                ("target", 32),
            ],
            &[("proto", 256), ("src_mac", 1024), ("reflection_zone", 256)],
        ),
        uci_read_with_options(
            "firewall_nat_configuration",
            1,
            UciReadProfile::FirewallNats,
            &[
                ("enabled", 8),
                ("name", 256),
                ("family", 32),
                ("src", 256),
                ("device", 256),
                ("src_ip", 1024),
                ("src_port", 256),
                ("snat_ip", 1024),
                ("snat_port", 256),
                ("dest_ip", 1024),
                ("dest_port", 256),
                ("limit", 64),
                ("limit_burst", 32),
                ("connlimit_ports", 8),
                ("utc_time", 8),
                ("start_date", 32),
                ("stop_date", 32),
                ("start_time", 32),
                ("stop_time", 32),
                ("weekdays", 128),
                ("mark", 64),
                ("counter", 8),
                ("log", 256),
                ("target", 32),
            ],
            &[("proto", 256)],
        ),
    ]
}
